### ISSUE TITLE
Server is unavailable, please try again in some time

### ISSUE THREAD

**Issue by madzae** [ans-4175/random-gofood-api#5]
Coba porting ke PHP, endpoint selalu menampilkan: 

`{ "errors": [ { "code": "HTTP_503", "message": "Server is unavailable, please try again in some time", "message_title": "Server Unavailable", "message_severity": "error" } ] }`

Endpoint yang saya gunakan: https://gofood.co.id/gofood/web/v1/restaurants

Kode PHP yang saya buat:

```
$date = date();

$curl = curl_init();

curl_setopt_array($curl, [
	CURLOPT_URL => "https://gofood.co.id/gofood/web/v1/restaurants",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_FOLLOWLOCATION => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "POST",
	CURLOPT_POSTFIELDS => "{\n  \"page\": \"1\",\n  \"collection\": \"NEAR_ME\",\n  \"search_id\": \"dfd92276-7123-4ac4-b927-d4a73894d357\",\n  \"date\": \"$date\",\n  \"format\": \"json\"\n}",
	CURLOPT_HTTPHEADER => [
		"X-location: -6.304378764325811, 106.85302734375001",
		"content-type: application/json"
	],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
	echo "cURL Error #:" . $err;
} else {
	echo $response;
}
```

**Comment by ans-4175** [comment]
Sebelumnya mohon maaf karena ini bukan issues, jadi aku close.
Disitu ada satu hal yang perlu @madzae cek (aku bukan ahli PHP)
- method request bukan POST, tapi GET
Coba itu dahulu.

Tapi setahuku curl_exec ini sync call, jadi mungkin ada masalah pemanggilan?
